version: "3.5"

services:
  web:
    build: .
    ports:
      - "8082:8082"
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
    command: go run main.go -b 0.0.0.0
    restart: always
  db:
    image: postgres:12.4-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=mysecretpassword
      - PGDATA=/var/lib/postgresql/data/pgdata
    restart: always