version: "3.5"

services:
  web:
    build: .
    env_file:
      - .env
    ports:
      - "8082:8082"
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
    command: air ./main.go -b 0.0.0.0
    restart: always
  db:
    image: postgres:12.4-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    restart: always
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
